# Generated by Django 3.2.5 on 2021-09-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('NombreUser', models.CharField(max_length=30)),
                ('NumeroUser', models.IntegerField(max_length=10)),
                ('EmailUsar', models.CharField(max_length=50)),
                ('Comentarios', models.CharField(max_length=80)),
            ],
        ),
    ]
