# Generated by Django 3.2.5 on 2021-09-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_comentarios_emailuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='NumeroUser',
            field=models.IntegerField(),
        ),
    ]
